# Generated by Django 5.0.1 on 2024-02-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('rejected', 'Rejected'), ('accepted', 'Accepted'), ('pending', 'Pending')], default='pending', max_length=200),
        ),
    ]
