# Generated by Django 5.0.1 on 2024-02-14 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='code',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 14, 6, 39, 54, 657233, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 14, 6, 39, 54, 657233, tzinfo=datetime.timezone.utc)),
        ),
    ]
