# Generated by Django 4.2.10 on 2024-02-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenstaff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='kitchenstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日'),
        ),
        migrations.AddField(
            model_name='restaurantstaff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='restaurantstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
