# Generated by Django 5.0.1 on 2024-02-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_kitchenstaff_created_at_kitchenstaff_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日'),
        ),
    ]
