# Generated by Django 5.0.1 on 2024-02-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_remove_food_unit_food_description_food_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='japan_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='myanmar_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
