# Generated by Django 5.0.1 on 2024-02-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_translation_food_japan_name_food_myanmar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='myanmar',
            field=models.TextField(blank=True),
        ),
    ]
